AllCops:
  Exclude:
    - "*.gemspec"

Metrics/AbcSize:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Exclude:
    - "spec/**/*"

Metrics/LineLength:
  Exclude:
    - "db/migrations/**"

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Style/MultilineOperationIndentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/ClassLength:
  Max: 200
